name: Automation Testing

on:
  schedule:
    - cron:  '0 22 * * *'
  
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/lock.json') }}
    - name: Installing
      run: npm install
    - name: Create folder reports
      run: mkdir reports
    - name: Running Test
      run: npm run test
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H.%M')"
    - name: Reporting
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Reports ${{ steps.date.outputs.date }}
        path: reports
